name: Copy to MongoDB

on:
  # Run after Product Hunt Crawler completes
  workflow_run:
    workflows: ["Product Hunt Crawler"]
    types:
      - completed
  # Allow manual triggering
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pymongo

    - name: Run copy script
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: python copyAgents.py
