name: Product Hunt Scraper

on:
  schedule:
    # Run every 3 days at midnight UTC
    - cron: '0 0 */3 * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Restore database from cache
        uses: actions/cache@v3
        with:
          path: |
            processed_urls.db
            product_hunt_metadata/
          key: ${{ runner.os }}-ph-database-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ph-database-
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
      
      - name: Modify scraper for stability
        run: |
          # Adjust MAX_URLS to process 10 at a time and disable browser restart
          sed -i 's/MAX_URLS = 1/MAX_URLS = 10/' scraper.py
          # Comment out browser restart code to prevent errors
          sed -i '/if (i + max_concurrent) < len(urls):/,/logger.error(f"Error restarting crawler: {e}")/s/^/# /' scraper.py
          
      - name: Run scraper
        run: python scraper.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add processed_urls.db product_hunt_metadata/ product_urls.txt scraper.log
          git diff --staged --quiet || git commit -m "Update data from scraper run on $(date)"
          git push